# Generated by Django 5.2.4 on 2025-09-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodev', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
