# Generated by Django 5.2.4 on 2025-09-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('service', models.CharField(blank=True, choices=[('individual therapy', 'Individual Therapy'), ('couples therapy', 'Couples Therapy'), ('corporate therapy', 'Corporate Therapy'), ('stress therapy', 'Stress Therapy'), ('depression therapy', 'Depression Therapy'), ('anxiety therapy', 'Anxiety Therapy')], max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('session', models.CharField(blank=True, choices=[('virtual', 'Virtual Session'), ('in_person', 'In-person Session'), ('group', 'Group Session')], max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
